In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
dataset=pd.read_csv('Amazon - Movies and TV Ratings.csv')
dataset.head()
X=dataset.iloc[:,1:].values

In [3]:
dataset.head()

          user_id  Movie1  Movie2  ...  Movie204  Movie205  Movie206
0  A3R5OBKS7OM2IR     5.0     5.0  ...       NaN       NaN       NaN
1   AH3QC2PC1VTGP     NaN     NaN  ...       NaN       NaN       NaN
2  A3LKP6WPMP9UKX     NaN     NaN  ...       NaN       NaN       NaN
3   AVIY68KEPQ5ZD     NaN     NaN  ...       NaN       NaN       NaN
4  A1CV1WROP5KTTW     NaN     NaN  ...       NaN       NaN       NaN

[5 rows x 207 columns]

In [4]:
dataset.describe()

       Movie1  Movie2  Movie3  Movie4  ...  Movie203  Movie204   Movie205   Movie206
count     1.0     1.0     1.0     2.0  ...       1.0  8.000000  35.000000  13.000000
mean      5.0     5.0     2.0     5.0  ...       3.0  4.375000   4.628571   4.923077
std       NaN     NaN     NaN     0.0  ...       NaN  1.407886   0.910259   0.277350
min       5.0     5.0     2.0     5.0  ...       3.0  1.000000   1.000000   4.000000
25%       5.0     5.0     2.0     5.0  ...       3.0  4.750000   5.000000   5.000000
50%       5.0     5.0     2.0     5.0  ...       3.0  5.000000   5.000000   5.000000
75%       5.0     5.0     2.0     5.0  ...       3.0  5.000000   5.000000   5.000000
max       5.0     5.0     2.0     5.0  ...       3.0  5.000000   5.000000   5.000000

[8 rows x 206 columns]

In [5]:
#Taking Care of NaN values
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,:])
X[:,:]=imputer.transform(X[:,:])

In [6]:
print(X)

[[5.         5.         2.         ... 4.375      4.62857143 4.92307692]
 [5.         5.         2.         ... 4.375      4.62857143 4.92307692]
 [5.         5.         2.         ... 4.375      4.62857143 4.92307692]
 ...
 [5.         5.         2.         ... 4.375      4.62857143 5.        ]
 [5.         5.         2.         ... 4.375      4.62857143 5.        ]
 [5.         5.         2.         ... 4.375      4.62857143 5.        ]]

In [7]:
df=dataset.melt(id_vars=["user_id"],var_name="MovieID",value_name="Ratings")
df

               user_id   MovieID  Ratings
0       A3R5OBKS7OM2IR    Movie1      5.0
1        AH3QC2PC1VTGP    Movie1      NaN
2       A3LKP6WPMP9UKX    Movie1      NaN
3        AVIY68KEPQ5ZD    Movie1      NaN
4       A1CV1WROP5KTTW    Movie1      NaN
...                ...       ...      ...
998683  A1IMQ9WMFYKWH5  Movie206      5.0
998684  A1KLIKPUF5E88I  Movie206      5.0
998685   A5HG6WFZLO10D  Movie206      5.0
998686  A3UU690TWXCG1X  Movie206      5.0
998687   AI4J762YI6S06  Movie206      5.0

[998688 rows x 3 columns]

In [ ]:
b=df.iloc[:,1:2].values

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
b=np.array(ct.fit_transform(b))

In [ ]:
from sklearn.model_selection import train_test_split
b_train,b_test,X_train,X_test=train_test_split(b,X,test_size=0.2,random_state=1)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(b,X)

In [ ]:
regressor.predict()